### ISSUE TITLE
datafeed delay when large no of instruments are subscribed

### ISSUE THREAD

**Issue by ghost** [krishnavelu/alice_blue#145]
A delay in datafeed is observed when no. of subscribed instruments are big, say more than 100,
I am receiving ticks with timestamp datetime.datetime(2020, 6, 24, 15, 18, 53) even after 15:32 (market close at 15:30).

steps to reproduce:

> start websocket
> subscribe more than 100 instruments
> compare the timestamp with current time after 30 minutes, latest available tick is delayed by approx 15 minutes.

event handler quote is as follows:
```
def event_handler_quote_update(tick):

    symbol = tick['instrument'].symbol
    timestamp =tick["exchange_time_stamp"]

    with open(f'D:/quant/data/tickdata/{symbol}.csv', 'a+') as f:
        f.write(f'{timestamp},{tick["ltp"]},{tick["volume"]}\n')

    print(f'delay : {(dt.datetime.now()-dt.datetime.fromtimestamp(timestamp)).total_seconds()}')
```

The delay I observed is proportional to no of subscribed instruments. The delay reduces if I unsubscribe some instruments and subsequently becomes near to 0 within 1 minute if subscribed instruments are less than 10.

I went to below thread but unable to get solution.
https://github.com/krishnavelu/alice_blue/issues/72#issue-584965793

**Comment by krishnavelu** [comment]
`event_handler_quote_update` function is called every time you get a quote update for each instruments. For example if you even get 3 ticks per symbol, per second that would be 300 times per second this function would be called. In actual this might be more as per actual ticks per symbol per seconds. So by calculation `event_handler_quote_update` function need to finish execution by 3.33ms. If not its going to get stacked up and execute late.
Try to measure each and every line you are executing inside `event_handler_quote_update` function. Also calculate the whole `event_handler_quote_update` function's execution time. Try to use a VPS instead of local laptop/desktop. Try increasing the power of VPS. There are lots of thing to be done in our side before we can get this issue to alice blue side. This performance measuring and improvements has no limits to it.

**Comment by ghost** [comment]
I have found this delay is not from aliceblue, or even network issue simply by running on Workstation with higher cpu freq.
This has to do something with threading as threads in python cannot utilize multiple cores because of GIL limitations in cPython.

**Comment by krishnavelu** [comment]
So what do you suggest?

**Comment by ghost** [comment]
multiprocessing can utilize multiple cores if available, but unable to figure out how to implement for websocket.

**Comment by krishnavelu** [comment]
So it's confirmed that its not a server issue. The library can only provide bare minimum which is needed to communicate to the server, which it already does. Remaining all stuffs should be done in application. If you feel that something should be added in this library which you feel is a must for everyone, then suggest the same & reopen this issue. Till then closing this.

**Comment by nrameshy** [comment]
@krishnavelu Do you have any suggestions to get live feed for 100+ scrips simultaneously?

**Comment by krishnavelu** [comment]
I've already given the explanation in above comments. If your code is efficient it can handle even more.
