### ISSUE TITLE
connect_timeout issue is coming.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#163]
I am getting connect_timeout issue intermittently. 
{'status': 'error', 'message': {'reason': 'connect_timeout', 'id': None, '_exception_': True}, 'data': {}}

**Comment by krishnavelu** [comment]
I’m also getting this, this week. Its a server issue. I cannot do anything in library if server disconnects.
Contact alice blue.

**Comment by jaydave1988** [comment]
I already contacted there.

Atleast we can fallback mechanism, in api_call_helper method.
If response is timed out then try after 5/10 seconds.

This issue is coming very often nowadays. And I am sure that after few seconds, it is working fine. 
So, if we add this fallback mechanism in our library, then user doesn't have to think about this.

**Comment by krishnavelu** [comment]
`{'status': 'error', 'message': {'reason': 'connect_timeout', 'id': None, 'exception': True}, 'data': {}}`
This is a message from server. Server itself gives are `connect_timeout`. `requests.get` is not getting timeout.
We already have re-connection mechanism in websoket. For `requests.get()` or `requests.post()` we don't have any because it would make it too complicated for multiple use cases. 
So I left it to the application to handle it.
