### ISSUE TITLE
Showing incorrect previous day closing price

### ISSUE THREAD

**Issue by ns931** [krishnavelu/alice_blue#168]
`alice.subscribe([alice.get_instrument_by_symbol('NSE', 'TATACONSUM')], LiveFeedType.MARKET_DATA)
alice.unsubscribe([alice.get_instrument_by_symbol('NSE', 'TATACONSUM')], LiveFeedType.MARKET_DATA)`

When used the above code to get the previous day closing price it shows day before yesterday closing price and at times it shows the expected value

<img width="745" alt="issue_pdc" src="https://user-images.githubusercontent.com/60307871/89612028-a61be880-d833-11ea-8861-7b81176ad080.PNG">

please look at the above screenshot where i have subscribed the data for TATACONSUM 
In first cell the closing price is 447.6 (day before yesterday) and in the second cell the closing price is 484.75 (yesterday) also you can observe the difference in the time from cell 1 and cell 2 is just 4 sec (exchange_time_stamp) where as the remaining values such as open, high, low are same

**Comment by krishnavelu** [comment]
Well captured.
Actually the ‘close’ price is previous day’s close. If market is on for a day all prices (open, high, low)are valid except close. Because close csn be determined only after market closes. So the actual close will be previous days close, till today’s close price is available.

Hope this explains why the price difference.

**Comment by krishnavelu** [comment]
Hope your problem is resolved. Reopen if needed.
