### ISSUE TITLE
OAuth 2.0 Error occurred. Please verify your api_secret

### ISSUE THREAD

**Issue by Mk2187** [krishnavelu/alice_blue#253]
i am getting this error

from alice_blue import *
import pdb
import datetime
import time
import  account_details

user_name = account_details.username
pass_word = account_details.password
two_FA = account_details.twoFA
API_secret = account_details.api_secret

API_id = '4n7uFCd9tWz'

access_token = AliceBlue.login_and_get_access_token(username= user_name, password= pass_word, twoFA= two_FA, redirect_url='https://ant.aliceblueonline.com/plugin/callback', api_secret= API_secret ,app_id=API_id)

print(access_token)

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by krishnavelu** [comment]
Hope your issue is resolved.

**Comment by krishnavelu** [comment]
- [x] Need to update README.md
- [x] Add getting BANKNIFTY and NIFTY spot instruments.

**Comment by Nerdion** [comment]
I am also facing the same issue. 

`access_token = AliceBlue.login_and_get_access_token(
    username=APIUSERNAME, password=PASSWORD, twoFA=TWOFA, api_secret=API_SECRET, app_id=APP_ID)`

Getting this error-
OAuth 2.0 Error occurred. Please verify your api_secret

**Comment by rahultandale3** [comment]
same error iwas facing OAuth 2.0
 Error occurred. Please verify your api_secret #253

and i got solution of this problem 
go and just check devloper api console redirect_url='https://ant.aliceblueonline.com/plugin/callback', , if this not then set it , otherwise your evething information is correct and stilll you wll get same error again and again 
@krishnavelu @Mk2187 @proritu 
#397
