### ISSUE TITLE
ERROR:alice_blue.alice_blue:OAuth 2.0 Error occurred. Please verify your api_secret

### ISSUE THREAD

**Issue by santoshmallik** [krishnavelu/alice_blue#314]
Hi,
I have executed the below command but getting the error message as mentioned below. I am correctly providing the API key.
Please suggest.

access_token = AliceBlue.login_and_get_access_token(username='username', password='password', twoFA='x',  api_secret='xxxxxxxx')

**ERROR:alice_blue.alice_blue:OAuth 2.0 Error occurred. Please verify your api_secret**

**Comment by krishnavelu** [comment]
Check with alice if your api is enabled.

**Comment by abhash2610** [comment]
Hi @krishnavelu . I am also getting the same error. Getting below error while debugging api:-

   `Error: invalid_request
   Description: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed
   Hint: The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.`

**Comment by krishnavelu** [comment]
Do the same.

**Comment by ayeeshaDevops** [comment]
Hi, 
I am also getting the same error.I have not received any mail from allice blue (regarding app secret enabling)

**Comment by ayeeshaDevops** [comment]
ERROR:alice_blue.alice_blue:OAuth 2.0 Error occurred. Please verify your api_secret

**Comment by krishnavelu** [comment]
Do the same

**Comment by Akshattanishq** [comment]
how to check the api secret is enabled or not?
