### ISSUE TITLE
Back testing

### ISSUE THREAD

**Issue by jayankp** [krishnavelu/alice_blue#317]
Hi Krishnavelu
How can I use Alice Blue and do back testing and test by algo logic.

**Comment by krishnavelu** [comment]
For back testing you need historical data. Which alice blue doesn’t provide. You can do only forward testing with this library.

**Comment by jayankp** [comment]
how can we do forward testing and not place actual orders. What I am looking for a is a mock place order and modify order calls so that I can test my algo before doing actual calls.

**Comment by krishnavelu** [comment]
There are 3 ways. Place actual orders
1. With just 1 quantity, so that your risk is very less.
2. With very high quantities. so that it gets rejected because you don't have enough funds. This is too risky. Understand this and place. Otherwise your account can wipe out to 0 if something wrong happens.
3. Write order entries to a text file, consolidate the order later in EOD.
