### ISSUE TITLE
Facing KEY_ERROR while requesting data 

### ISSUE THREAD

**Issue by codewithraviteja** [krishnavelu/alice_blue#360]
Hello, am facing an error called "KeyError" while am requesting the data in while loop. There is an order in the pending order list and I am requesting the data but after sometime, it gives "KeyError". Please check the below picture. Thank you in advance.

![Screenshot_102](https://user-images.githubusercontent.com/57951049/141929401-294f4877-fff6-4f4c-9659-14a18ac73fba.png)

**Comment by krishnavelu** [comment]
This is a general python issue. If that key is not available in the dict, you'll get key error.

**Comment by codewithraviteja** [comment]
If the key is not found, first iteration itself it was supposed to fail but here in the given picture first two Iteration, it was successfully gave data but third iteration, it gave error. Please check the picture I have attached

**Comment by krishnavelu** [comment]
Learn python…

**Comment by codewithraviteja** [comment]
I am sorry Krishnavelu, You have misunderstood me. I am requesting the data while the order is in pending orders. I know it will generate key error if the dictionary is empty but am requesting the data when there is a pending order. Please understand. Even though there is a pending order, it gave key error while am running it in loop. Please check the picture once. 
![Screenshot_102](https://user-images.githubusercontent.com/57951049/142008337-26056b2b-3a5d-4d12-9211-619258354faf.png)

**Comment by krishnavelu** [comment]
What will happen if the order is not pending? Why don't you print and see the dict itself instead of guessing it has pending orders or not?

**Comment by codewithraviteja** [comment]
I know that If the order is not pending, it will simply show an empty list. I am not guessing it, I am calling the "get_pending_orders" variable in a loop when there is a pending order. After printing the list two times, the third time it gave key error instead of printing the  list again. check the picture.

**Comment by krishnavelu** [comment]
I said print the whole dict and see. Not only pending_order key.

**Comment by codewithraviteja** [comment]
This is how it shows. Please check the picture

![Screenshot_103](https://user-images.githubusercontent.com/57951049/142210094-00b9550b-8040-4230-8404-2d78b1c9785e.png)

**Comment by krishnavelu** [comment]
Did you get an error now?

**Comment by codewithraviteja** [comment]
No, I did not.

**Comment by krishnavelu** [comment]
So your key_error : pending_order problem is solved.

**Comment by codewithraviteja** [comment]
No, it didn't solved. The topic was completed diverted. I know that Key error only occurs when we attempt to access an item in a dictionary that does not exist using the indexing syntax right?. But am accessing the pending order item when there is a pending order. So in the first given picture, am accessing the correct item which was in a loop and it was printed for 2 times and then it stopped running and shows "Key Error". Please again check the first picture. I think you are confusing.

**Comment by krishnavelu** [comment]
You are trying to deviate from the intention of this forum. This forum is to report/resolve any errors bugs related to this library only. Not for your application. `alice.get_order_history()` is using this library. If you found any problem, you can create an issue and report. `alice.get_order_history()['data']['pending_orders']` is your own application, try to understand the difference. I won't and cannot help for your own application. That's why my most of the reply would be just 'Learn python'. If I try to help beyond that, The conversation just goes on and on wasting my time.
If you find any problem using this library, read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow, provide me what I need to reproduce the issue in my side while creating a new issue. 
In your case this issue was created for ` key_error : pending_order`. the first 2 time pending_order key was there in the dict. The third time you got an error. That means that dict didn't have `pending_order`. What It was in the dict? I don't know, you don't know. Because you didn't print. Without knowing what's in the dict you are trying to access a key directly.
If you want to know if that key is in the dict, it a simple code `if 'key' in dict`. 
Again Learn python and jump to automated trading before making your account 0.
