### ISSUE TITLE
Aliceblue object creation taking too much time 

### ISSUE THREAD

**Issue by danishXcode** [krishnavelu/alice_blue#433]
It takes around 6 second while creating the object  and this object cant be reused for multiple request, not sure why

**Comment by krishnavelu** [comment]
yes, it takes more time, this depends upon your computer's speed and internet connection.
What do you mean by `cant be reused for multiple request` ?

**Comment by danishXcode** [comment]
`What do you mean by can't be reused for multiple requests?`  If I Create Aliceblue Object as a Global  and place a trade then Cant reuse it for next trade

**Comment by krishnavelu** [comment]
You can reuse for a day.

**Comment by danishXcode** [comment]
{"status":"error","message":"Request Unauthorised , Session Expired From Backend","data":{}} I get this message when I reuse AliceObject after 5 mins of creation

**Comment by aeron7** [comment]
Hi @danishXcode , It is because the API is not utilizing their V2 Updates.  Thats why it keeps getting logged out.

Right now there is no intention of updating or maintaining this API at all. We are an official strategic partner of Aliceblue and initially communicated and agreed to maintain and develop AliceBlue Python API along with its ecosystem.

@krishnavelu developed the API. They put this repo link on their main website. **Now, they have removed it from the main website.**

Now they have copied this code shamelessly and "tried" to make their own API.

**So, Either they have to put this library as an official library on their website. Or, they can make their own library themselves.**
