### ISSUE TITLE
Candle data

### ISSUE THREAD

**Issue by tanajeek** [krishnavelu/alice_blue#467]
Can we get realtime 5 min candle data (high low open close)  for current and previous candle ?

**Comment by krishnavelu** [comment]
Did you read the complete document?

**Comment by aeron7** [comment]
> Can we get realtime 5 min candle data (high low open close) for current and previous candle ?

Just store the LTPs from the websocket and make 5min candle data. Websocket gives live data only.

**Comment by selvaks030** [comment]
I am inserting the LTP and created candles as well but the issue is real time candle and mine is not matching

On checking further, I noticed some timing gap issue is there for me

For example , I see 85.50000 Rs inserted in my db (mysql)  on 2022-09-29 14:53:14 for BANKNIFTY SEP 37700.0 PE ( Sep 29 Expiry )  but when i see Alice blue chart the price was around 40 to 60 from 2 mins before.

No idea how did this happen.. Could you pls help on this

**Comment by aeron7** [comment]
That's Aliceblue's WSS's code fault. You get what their server throws. Right? Their server is throwing it that price. Our code just is a wrapper that reads that. Contact the aliceblue team. This new API's primary problem amongst the user is this delay.
