### ISSUE TITLE
Base URL not responding https://a3.aliceblueonline.com/rest/AliceBlueAPIService

### ISSUE THREAD

**Issue by jayaraj007007** [krishnavelu/alice_blue#506]
In the alice_blue.py file I can see the Base URL used as https://a3.aliceblueonline.com/rest/AliceBlueAPIService which is not responding, and in the official documentation the base URL is referred as https://ant.aliceblueonline.com/rest/AliceBlueAPIService/api/. Let me know if anyone not facing any issues.

![image](https://user-images.githubusercontent.com/24728032/236527782-e96c660c-b0c5-4019-9bbd-621aad97fa5b.png)

**Comment by bhooshanmate** [comment]
It is possible that there is a typo in the first URL (https://a3.aliceblueonline.com/rest/AliceBlueAPIService) or that it is an older version of the API service.
It is also possible that the "a3" URL is a staging or testing environment and not meant for production use.
Please use the other URL (https://ant.aliceblueonline.com/rest/AliceBlueAPIService/api/) as base url , this one works when used with correct endpoint.

**Comment by krishnavelu** [comment]
@jayaraj007007  @bhooshanmate  a3.aliceblueonline was the original one and working. Alice might've changed it now.
I've changed in develop branch. 
Please test and let me know if its working, I'm not able to test it.

**Comment by bhooshanmate** [comment]
@krishnavelu yes it's working now.

**Comment by pupattan** [comment]
Does not look like anything is working

**Comment by krishnavelu** [comment]
@pupattan  what's the issue?

**Comment by rajeshjoshi8792** [comment]
i m facing same issue. please give me solution.

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='a3.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x103d4c390>: Failed to resolve 'a3.aliceblueonline.com' ([Errno 8] nodename nor servname provided, or not known)"))


i already tried to change the base url from a3 to ant. but still it didnt worked.
