### ISSUE TITLE
Websocket timestamp format

### ISSUE THREAD

**Issue by rishiajmera** [krishnavelu/alice_blue#84]
Hello,
I am trying to convert the exchange timestamp into a string but facing issue with inconsistent timezone I guess. Sometimes, it's giving based on IST and sometimes, it is giving data with some other timezone.
Can you please share what is the right way to convert the timestamp into a string with IST timezone?

**Comment by krishnavelu** [comment]
Provide more info on what you are referring to and things to reproduce.

**Comment by rishiajmera** [comment]
datetime.fromtimestamp(message['exchange_time_stamp']).strftime('%H:%M:%S')

I am trying to convert timestamp into the string using the above syntax. But it doesn't give the correct timestamp every time. I have tried several other methods but its same. Looks like timezone is not consistent in WebSocket data.

**Comment by krishnavelu** [comment]
What response you are getting from server?

**Comment by krishnavelu** [comment]
Use this [link](https://www.unixtimestamp.com/index.php) to convert time stamp.

**Comment by rishiajmera** [comment]
Yes, but can you please suggest how can we convert in python?

**Comment by krishnavelu** [comment]
Search in google.

**Comment by rishiajmera** [comment]
Bro, I know all the methods to convert the timestamp. The issue is it's converting into different timezone every time. There can be some issue from your end that it's sending timestamps with a different timezone at different times. This could be a serious issue if my doubt is True. 
I have also suggested you about order tag which you have added as a milestone. If you read that thread, you ignored me initially and I had to explain to you its important to you and then you added it to the milestone. 
Anyways, I know you guys are more worried about your business than me so I will not push you any more.
Thanks for the help! Cheers.
Regards,
Rishi A.

**Comment by rishiajmera** [comment]
I know all the methods to convert the timestamp. The issue is, it's converting into a different timezone at different times. It is possible that you guys are sending timestamps with different timezones at different times. If that is the case, we can't solve it by googling from our end. Please provide some resolution.

**Comment by krishnavelu** [comment]
> Bro, I know all the methods to convert the timestamp. The issue is it's converting into different timezone every time. There can be some issue from your end that it's sending timestamps with a different timezone at different times. This could be a serious issue if my doubt is True.

This library is just a bridge for communicating to alice server. If you feel my library is doing something wrong and converting timestamps, provide me results/responses from library. I'll be happy to fix it. Most probably its not library, its just response from the server. If its response from the server you need to contact alice.

> I have also suggested you about order tag which you have added as a milestone. If you read that thread, you ignored me initially and I had to explain to you its important to you and then you added it to the milestone.

I didn't ignore you, When I was creating this library, I deliberately suppressed `order_tag` as `order1` because I didn't find a valid use case at that time. When I was asking questions in that thread, I was asking about a valid use case, which you gave. And then I've added to milestone.

> Anyways, I know you guys are more worried about your business than me so I will not push you any more.

What business you are talking about? `Alice Blue` ? I'm no where affiliated with `Alice Blue` broker. I'm an individual who contributed this library to public for **free**.

If you find any bug in my library, provide me details/results, I'll be happy to fix it. If you need a new feature, provide me a valid use case, I'll be happy to develop that too. You can ask me any doubt on how to use this library (before asking see documentation and other issues) why this library is behaving like this/that. Other than this if you as any general query like how to do this/that in python my answer will be `Search google`. My answers will be looking short and rude, but in actual its not.

Still in this issue, I didn't find a single response/result form the library which I'm expecting. Like what you are doing? (a sample code) and what you are getting as response? 
All are just descriptions. Till now what I got your problem is `How to convert the exchange timestamp into a string`.

**Comment by rishiajmera** [comment]
Hi bro,
I thought you're officially handling this python wrapper for Aliceblue. Really sorry about that, I should have checked it first before telling you such a thing. All my replied were with that impression in my mind. 

For this timestamp issue, I think I will talk to Aliceblue support for this as I think the issue is with the data they are providing. I knew it before, but I was thinking that this is official Aliceblue python wrapper, I was posting it here. Again sorry for it.

If you are doing it for free, then your replies are not at all rude. People should not and can not expect a detailed answer from you for everything. 

In future, if I find any issue/bug,  I will definitely write a detailed answer with my code to reduce efforts from your side. 

Thanks for doing great work! Apologies again.

Regards,
Rishi A.

**Comment by hyndex** [comment]
We should encourage such people..thnx Bro @krishnavelu

**Comment by vijayraj-saaras** [comment]
I think you can convert it like this,

df['date']=pd.to_datetime(df['date'],unit='s')
df=df.set_index(['date'])
df = df.tz_localize('UTC').tz_convert('Asia/Kolkata')
