### ISSUE TITLE
Need to implement wesocket re-connection mechanism after disconnection.

### ISSUE THREAD

**Issue by krishnavelu** [krishnavelu/alice_blue#9]
Need to implement websocket re-connection mechanism after disconnection. This can solve issue #6 .

**Comment by vikram477** [comment]
KrishNa Sir 
                   I write algo in python using your reference code(main.py) and deploy it on amazon cloud 15 day ago .
 But as I start program in morning after some time LTP not get refreshed web socket already closed appear. I come to know there need to send heartbeat every 10 second otherwise web socket get closed .
My problem is how to code in PYTHON to send heart beats and rectify this problem completely plz help me on this issue
